<a href="https://colab.research.google.com/github/ChengHanChiu/imtku_for_dial_eval_1/blob/develop/bert_intent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""
參考文章:https://leemeng.tw/attack_on_bert_transfer_learning_in_nlp.html
"""

'\n參考文章:https://leemeng.tw/attack_on_bert_transfer_learning_in_nlp.html\n'

In [0]:
%%bash
pip install transformers tqdm boto3 requests regex -q

In [0]:
import torch
from transformers import BertTokenizer

PRETRAINED_MODEL_NAME = "bert-base-chinese" # 指定繁簡中文 BERT-BASE 預訓練模型

# 取得此預訓練模型所使用的 tokenizer
tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)

print("PyTorch 版本:",torch.__version__)

PyTorch 版本: 1.4.0


In [0]:
vocab = tokenizer.vocab
print("字典大小:",len(vocab))

字典大小: 21128


In [0]:
import random
random_tokens = random.sample(list(vocab),10)
random_ids = [vocab[t] for t in random_tokens]  #index如何產生??
print("{0:20}{1:15}".format("token","index"))
print("-" * 25)
for t,id in zip(random_tokens,random_ids): #zip:將兩個list包裝成一組
    print("{0:15}{1:10}".format(t,id))


token               index          
-------------------------
##姬                 15067
歇                    3623
2050                11931
v9                  11894
##祎                 17916
##ico               10641
##sion               9224
##掬                 16032
##db                 9123
##证                 19452


In [0]:
text = "[cls]等到潮水退了，就知道誰沒穿褲子。"
tokens = tokenizer.tokenize(text)
ids = tokenizer.convert_tokens_to_ids(tokens)

print(text)
print(tokens)
print(ids)

[cls]等到潮水退了，就知道誰沒穿褲子。
['[', 'cl', '##s', ']', '等', '到', '潮', '水', '退', '了', '，', '就', '知', '道', '誰', '沒', '穿', '褲', '子', '。']
[138, 12847, 8118, 140, 5023, 1168, 4060, 3717, 6842, 749, 8024, 2218, 4761, 6887, 6306, 3760, 4959, 6194, 2094, 511]


In [0]:
"""(以下程式碼未更改，非重點)"""
# 安裝 BertViz
import sys
!test -d bertviz_repo || git clone https://github.com/jessevig/bertviz bertviz_repo
if not 'bertviz_repo' in sys.path:
  sys.path += ['bertviz_repo']

# import packages
from transformers import BertTokenizer, BertModel
from bertviz import head_view

# 在 jupyter notebook 裡頭顯示 visualzation 的 helper
def call_html():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              "d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.8/d3.min",
              jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
            },
          });
        </script>
        '''))


In [0]:
"""(以下程式碼未更改，非重點)"""
model_version = 'bert-base-chinese'
model = BertModel.from_pretrained(model_version, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained(model_version)

# 情境 1 的句子
sentence_a = "胖虎叫大雄去買漫畫，"
sentence_b = "回來慢了就打他。"

# 得到 tokens 後丟入 BERT 取得 attention
inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', add_special_tokens=True)
token_type_ids = inputs['token_type_ids']
input_ids = inputs['input_ids']
attention = model(input_ids, token_type_ids=token_type_ids)[-1]
input_id_list = input_ids[0].tolist() # Batch index 0
tokens = tokenizer.convert_ids_to_tokens(input_id_list)
call_html()

# 交給 BertViz 視覺化
head_view(attention, tokens)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [0]:
'''註解
import pandas as pd
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

link = 'https://drive.google.com/open?id=1TJgNlWSBofcd7qCOcR4ZTozXOXz2fF4Z' 
# The shareable link
fluff, id = link.split('=')
print (id) 
# Verify that you have everything after '='
#取得Dataframe
downloaded1 = drive.CreateFile({'id':id}) 
downloaded1.GetContentFile('train.csv') 

df_train = pd.read_csv('train.csv')
# Dataset is now stored in a Pandas Dataframe

print("訓練樣本數：", len(df_train))
df_train.head(20)
註解'''

'註解\nimport pandas as pd\n# Code to read csv file into Colaboratory:\n!pip install -U -q PyDrive\nfrom pydrive.auth import GoogleAuth\nfrom pydrive.drive import GoogleDrive\nfrom google.colab import auth\nfrom oauth2client.client import GoogleCredentials\n# Authenticate and create the PyDrive client.\nauth.authenticate_user()\ngauth = GoogleAuth()\ngauth.credentials = GoogleCredentials.get_application_default()\ndrive = GoogleDrive(gauth)\n\nlink = \'https://drive.google.com/open?id=1TJgNlWSBofcd7qCOcR4ZTozXOXz2fF4Z\' \n# The shareable link\nfluff, id = link.split(\'=\')\nprint (id) \n# Verify that you have everything after \'=\'\n#取得Dataframe\ndownloaded1 = drive.CreateFile({\'id\':id}) \ndownloaded1.GetContentFile(\'train.csv\') \n\ndf_train = pd.read_csv(\'train.csv\')\n# Dataset is now stored in a Pandas Dataframe\n\nprint("訓練樣本數：", len(df_train))\ndf_train.head(20)\n註解'

In [0]:
from google.colab import drive
import pandas as pd

drive.mount('/content/gdrive') # 此處需要登入google帳號
# 獲取授權碼之後輸入即可連動雲端硬碟
%cd '/content/gdrive/My Drive/Colab Notebooks'

# df_train = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/train.csv")
# 取得Dataframe
df_train = pd.read_csv('train.csv') # 訓練資料
# Dataset is now stored in a Pandas Dataframe

print("訓練樣本數：", len(df_train))
df_train.head(20)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/My Drive/Colab Notebooks
訓練樣本數： 3701


text intent
0      告訴我從費城飛往達拉斯的是停在亞特蘭大的航班     機票
1          我需要從巴爾的摩飛往達拉斯星期二晚上     飛行
2          從紐瓦克飛往克里夫蘭每天下午5點航班     飛行
3              給我的波士頓和丹佛之間的航班     飛行
4      讓我從舊金山到波士頓費城或巴爾的摩的所有航班     飛行
5               顯示波士頓和丹佛之間的航班     飛行
6      什麼是週三的最新航班會從亞特蘭大到華盛頓特區     飛行
7    什麼是從巴爾的摩到舊金山週五八月三十最便宜的機票     飛行
8   I'd像從丹佛一張票，亞特蘭大與匹茲堡停留這是可能     機票
9     我想舊金山美國航空公司航班從巴爾的摩在丹佛停止     機票
10  什麼是車費去的一種方式在十一月十七從丹佛飛往奧克蘭     飛行
11      有沒有在美國聯合航空公司從波士頓到丹佛航班     機票
12            告訴我從費城到亞特蘭大晚上航班     飛行
13            給我看在費城地面上週一早上交通     飛行
14     我想從多倫多到聖地亞哥的美國飛機在丹佛停留請     飛行
15       什麼才是從奧克蘭最便宜的單程飛行到波士頓     飛行
16             我想從巴爾的摩飛往達拉斯往返     飛行
17         告訴我，從亞特蘭大到匹茲堡的航班單程     飛行
18             上週日從坦帕飛往夏洛特的航班     飛行
19       找到從達拉斯往返航班飛往匹茲堡的行程安排     飛行

In [0]:
df_train.intent.value_counts() / len(df_train) # 看訓練集每個intent的比例

飛行       0.781410
機票       0.090516
航空公司     0.033234
縮寫       0.031343
飛機       0.017293
飛行時間     0.010808
數量       0.009457
航班機票+    0.004593
市        0.004593
距離       0.004053
飛機場      0.004053
容量       0.003242
航班號      0.002432
限制       0.001351
膳食       0.001351
最便宜      0.000270
Name: intent, dtype: float64

In [0]:
# df_test = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/test.csv")
# 取得Dataframe
df_test = pd.read_csv('test.csv') # 測試資料
# Dataset is now stored in a Pandas Dataframe

print("訓練樣本數：", len(df_test))
df_test.head(20)

訓練樣本數： 999


text intent
0        我想在838分從波士頓飛，並在1110上午在抵達丹佛   飛行時間
1              哪些航班可以從匹茲堡飛往巴爾的摩週四上午     飛行
2           什麼是在舊金山的到貨時間為755班機離開華盛頓     飛行
3                    最廉價的機票從塔科馬到奧蘭多   飛行時間
4                  從匹茲堡在1000元往返車費費城     機票
5               我需要一個航班從明天哥倫布明尼阿波利斯     機票
6             什麼樣的飛機是從克利夫蘭到達拉斯的飛行使用     飛行
7                   告訴我從匹茲堡到洛杉磯週四航班     飛機
8                     從波士頓到華盛頓的所有航班     飛行
9                      什麼樣的地面交通丹佛可用     飛行
10              讓我從圣迭戈到紐瓦克的航班由休斯敦方式     飛行
11                     還有什麼意義在奧蘭多機場     飛行
12              什麼是從波士頓到華盛頓國際最便宜的航班    飛機場
13                    所有航班巴爾的摩下午6時後     飛行
14                   給我頭等艙票價從波士頓到丹佛     飛行
15                      告訴我在丹佛的地面交通     機票
16  我需要的航班信息，週二離開巴爾的摩達拉斯波士頓和波士頓巴爾的摩     飛行
17             請給我從波士頓飛往匹茲堡的航班下週的週四     飛行
18                我想從丹佛飛往匹茲堡的聯合航空公司     飛行
19                    讓我從圣迭戈到紐瓦克的航班     飛行

In [0]:
"""
# idempotence, 將處理結果另存成 tsv 供 PyTorch 使用
df_train.to_csv("train.tsv", sep="\t", index=False)  #??

from google.colab import files
files.download("train.tsv")
"""

'\n# idempotence, 將處理結果另存成 tsv 供 PyTorch 使用\ndf_train.to_csv("train.tsv", sep="\t", index=False)  #??\n\nfrom google.colab import files\nfiles.download("train.tsv")\n'

In [0]:
!ls


 bert_intent.ipynb	        SFID程式碼		   train.csv
'Copy of bert.ipynb'	        Simple_CNN_Cifar10.ipynb   train.tsv
'Copy of NTUBertTest.ipynb'     test.csv
 SF-ID-Network-For-NLU-master   test.tsv


In [0]:
""" 
此 Dataset 每次將 tsv 裡的一筆成對句子轉換成 BERT 相容的格式，並回傳 3 個 tensors：
- tokens_tensor：兩個句子合併後的索引序列，包含 [CLS] 與 [SEP]
- segments_tensor：可以用來識別兩個句子界限的 binary tensor 
- label_tensor：將分類標籤轉換成類別索引的 tensor, 如果是測試集則回傳 None
"""
"""
如果輸入只有一個句子就將segments_tensor全部設為0。
!!錯誤:segments_tensor = 0 。
換成segments_tensor = torch.tensor([0] * length, dtype=torch.long) 就OK了 (edited)

參考:https://www.cnblogs.com/d0main/p/10447853.html#%E5%AE%9E%E7%8E%B0
"""
from torch.utils.data import Dataset

class ATIS_zh_Dataset(Dataset):
    # 讀取前處理後的 tsv 檔並初始化一些參數
    def __init__(self, mode ,tokenizer):
        assert mode in ["train" , "test"] # 如果mode不等於這兩個，assert Exception
        self.mode = mode
        self.df = pd.read_csv(mode + ".tsv" , sep="\t").fillna("")
        self.len = len(self.df)
        self.intent_map = {"市":0,"限制":1,"飛行":2,"飛行時間":3,"飛機":4,"飛機場":5,"容量":6,"航空公司":7,"航班號":8,"航班機票+":9,"最便宜":10,"距離":11,"數量":12,"機票":13,"膳食":14,"縮寫":15}
        self.tokenizer = tokenizer

     # 定義回傳一筆訓練 / 測試數據的函式
    def __getitem__(self , index):
        if self.mode == "test":
            text = self.df.iloc[index].values #???
            intent_tensor = None
        else:
            text, intent = self.df.iloc[index, :].values
            # 將 label 文字也轉換成索引方便轉換成 tensor
            intent_id = self.intent_map[intent]
            intent_tensor = torch.tensor(intent_id)
        
        word_pieces = ["[CLS]"]
        tokens = self.tokenizer.tokenize(text)
        word_pieces += tokens 
        length = len(word_pieces)

        # 將第一句包含 [SEP] 的 token 位置設為 0，其他為 1 表示第二句
        segments_tensor = torch.tensor([0] * length, 
                                        dtype=torch.long)
        
        # 將整個 token 序列轉換成索引序列
        indexs = self.tokenizer.convert_tokens_to_ids(word_pieces)
        tokens_tensor = torch.tensor(indexs)

        return(tokens_tensor,segments_tensor,intent_tensor)
      
    def __len__(self):
        return self.len
        
# 初始化一個專門讀取訓練樣本的 Dataset，使用中文 BERT 斷詞
trainset = ATIS_zh_Dataset("train", tokenizer=tokenizer)


# print(trainset[0])
# print(trainset[0][2])




(tensor([ 101, 1440, 6260, 2769, 2537, 6527, 1814, 7606, 2518, 6888, 2861, 3172,
        4638, 3221,  977, 1762,  765, 4294, 5984, 1920, 4638, 5661, 4408]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), tensor(13))
tensor(13)


In [0]:
# 選擇第一個樣本
sample_idx = 0

# 將原始文本拿出做比較
text, intent = trainset.df.iloc[sample_idx].values

# 利用剛剛建立的 Dataset 取出轉換後的 id tensors
tokens_tensor, segments_tensor, intent_tensor = trainset[sample_idx]

# 將 tokens_tensor 還原成文本
tokens = tokenizer.convert_ids_to_tokens(tokens_tensor.tolist())
combined_text = "".join(tokens)

# 渲染前後差異
print(f"""[原始文本]
句子 1：{text}
分類  ：{intent}

--------------------

[Dataset 回傳的 tensors]
tokens_tensor  ：{tokens_tensor}

segments_tensor：{segments_tensor}

label_tensor   ：{intent_tensor}

--------------------

[還原 tokens_tensors]
{combined_text}
""")

[原始文本]
句子 1：告訴我從費城飛往達拉斯的是停在亞特蘭大的航班
分類  ：機票

--------------------

[Dataset 回傳的 tensors]
tokens_tensor  ：tensor([ 101, 1440, 6260, 2769, 2537, 6527, 1814, 7606, 2518, 6888, 2861, 3172,
        4638, 3221,  977, 1762,  765, 4294, 5984, 1920, 4638, 5661, 4408])

segments_tensor：tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

label_tensor   ：13

--------------------

[還原 tokens_tensors]
[CLS]告訴我從費城飛往達拉斯的是停在亞特蘭大的航班



In [0]:
"""
實作可以一次回傳一個 mini-batch 的 DataLoader
這個 DataLoader 吃我們上面定義的 `FakeNewsDataset`，
回傳訓練 BERT 時會需要的 4 個 tensors：
- tokens_tensors  : (batch_size, max_seq_len_in_batch)
- segments_tensors: (batch_size, max_seq_len_in_batch)
- masks_tensors   : (batch_size, max_seq_len_in_batch)
- label_ids       : (batch_size)
"""

from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pad_sequence

# 這個函式的輸入 `samples` 是一個 list，裡頭的每個 element 都是
# 剛剛定義的 `ATIS_zh_Dataset` 回傳的一個樣本，每個樣本都包含 3 tensors：
# - tokens_tensor
# - segments_tensor
# - label_tensor
# 它會對前兩個 tensors 作 zero padding，並產生前面說明過的 masks_tensors

def create_mini_batch(samples):
    tokens_tensors = [s[0] for s in samples]
    segments_tensors = [s[1] for s in samples]
    

    # 測試集有 labels
    if samples[0][2] is not None:
        label_ids = torch.stack([s[2] for s in samples])
    else:
        label_ids = None
    
    # zero pad 到同一序列長度
    tokens_tensors = pad_sequence(tokens_tensors, 
                                  batch_first=True)
    segments_tensors = pad_sequence(segments_tensors, 
                                    batch_first=True)
    
    # attention masks，將 tokens_tensors 裡頭不為 zero padding
    # 的位置設為 1 讓 BERT 只關注這些位置的 tokens
    masks_tensors = torch.zeros(tokens_tensors.shape, 
                                dtype=torch.long)
    masks_tensors = masks_tensors.masked_fill(
        tokens_tensors != 0, 1)
    
    return tokens_tensors, segments_tensors, masks_tensors, label_ids


# 初始化一個每次回傳 64 個訓練樣本的 DataLoader
# 利用 `collate_fn` 將 list of samples 合併成一個 mini-batch 是關鍵
BATCH_SIZE = 64
trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, 
                         collate_fn=create_mini_batch)

In [0]:
data = next(iter(trainloader)) 

tokens_tensors, segments_tensors, masks_tensors, label_ids = data

print(f"""
tokens_tensors.shape   = {tokens_tensors.shape} 
{tokens_tensors}
------------------------
segments_tensors.shape = {segments_tensors.shape}
{segments_tensors}
------------------------
masks_tensors.shape    = {masks_tensors.shape}
{masks_tensors}
------------------------
label_ids.shape        = {label_ids.shape}
{label_ids}
""")


tokens_tensors.shape   = torch.Size([64, 33]) 
tensor([[ 101, 1440, 6260,  ...,    0,    0,    0],
        [ 101, 2769, 7444,  ...,    0,    0,    0],
        [ 101, 2537, 5153,  ...,    0,    0,    0],
        ...,
        [ 101,  828, 3172,  ...,    0,    0,    0],
        [ 101,  784, 7938,  ...,    0,    0,    0],
        [ 101, 2769, 1762,  ...,    0,    0,    0]])
------------------------
segments_tensors.shape = torch.Size([64, 33])
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])
------------------------
masks_tensors.shape    = torch.Size([64, 33])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
------------------------
label_ids.shape        

In [0]:
from transformers import BertForSequenceClassification

PRETRAINED_MODEL_NAME = "bert-base-chinese"
NUM_LABELS = 16 

model = BertForSequenceClassification.from_pretrained(PRETRAINED_MODEL_NAME,
                                                      num_labels=NUM_LABELS)

print("""
name            module
----------------------""")
for name, module in model.named_children():
    if name == "bert":
        for n, _ in module.named_children():
            print(f"{name}:{n}")
    else:
        print("{:15} {}".format(name, module))


name            module
----------------------
bert:embeddings
bert:encoder
bert:pooler
dropout         Dropout(p=0.1, inplace=False)
classifier      Linear(in_features=768, out_features=16, bias=True)


In [0]:
""" (以下程式碼未更改)
定義一個可以針對特定 DataLoader 取得模型預測結果以及分類準確度的函式
之後也可以用來生成上傳到 Kaggle 競賽的預測結果

2019/11/22 更新：在將 `tokens`、`segments_tensors` 等 tensors
丟入模型時，強力建議指定每個 tensor 對應的參數名稱，以避免 HuggingFace
更新 repo 程式碼並改變參數順序時影響到我們的結果。
"""

def get_predictions(model, dataloader, compute_acc=False):
    predictions = None
    correct = 0
    total = 0
      
    with torch.no_grad():
        # 遍巡整個資料集
        for data in dataloader:
            # 將所有 tensors 移到 GPU 上
            if next(model.parameters()).is_cuda:
                data = [t.to("cuda:0") for t in data if t is not None]
            
            
            # 別忘記前 3 個 tensors 分別為 tokens, segments 以及 masks
            # 且強烈建議在將這些 tensors 丟入 `model` 時指定對應的參數名稱
            tokens_tensors, segments_tensors, masks_tensors = data[:3]
            outputs = model(input_ids=tokens_tensors, 
                            token_type_ids=segments_tensors, 
                            attention_mask=masks_tensors)
            
            logits = outputs[0]
            _, pred = torch.max(logits.data, 1)
            
            # 用來計算訓練集的分類準確率
            if compute_acc:
                labels = data[3]
                total += labels.size(0)
                correct += (pred == labels).sum().item()
                
            # 將當前 batch 記錄下來
            if predictions is None:
                predictions = pred
            else:
                predictions = torch.cat((predictions, pred))
    
    if compute_acc:
        acc = correct / total
        return predictions, acc
    return predictions
    
# 讓模型跑在 GPU 上並取得訓練集的分類準確率
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device)
model = model.to(device)
_, acc = get_predictions(model, trainloader, compute_acc=True)
print("classification acc:", acc)

device: cuda:0
classification acc: 0.2696568495001351


In [0]:
"""(以下程式碼未更改，非重點)"""
def get_learnable_params(module):
    return [p for p in module.parameters() if p.requires_grad]
     
model_params = get_learnable_params(model)
clf_params = get_learnable_params(model.classifier)

print(f"""
整個分類模型的參數量：{sum(p.numel() for p in model_params)}
線性分類器的參數量：{sum(p.numel() for p in clf_params)}
""")


整個分類模型的參數量：102279952
線性分類器的參數量：12304



In [0]:
%%time

# 訓練模式
model.train()

# 使用 Adam Optim 更新整個分類模型的參數
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)


EPOCHS = 20  # 訓練次數
for epoch in range(EPOCHS):
    
    running_loss = 0.0
    for data in trainloader:
        
        tokens_tensors, segments_tensors, \
        masks_tensors, labels = [t.to(device) for t in data]

        # 將參數梯度歸零
        optimizer.zero_grad()
        
        # forward pass
        outputs = model(input_ids=tokens_tensors, 
                        token_type_ids=segments_tensors, 
                        attention_mask=masks_tensors, 
                        labels=labels)

        loss = outputs[0]
        # backward
        loss.backward()
        optimizer.step()


        # 紀錄當前 batch loss
        running_loss += loss.item()
        
    # 計算分類準確率
    _, acc = get_predictions(model, trainloader, compute_acc=True)

    print('[epoch %d] loss: %.3f, acc: %.3f' %
          (epoch + 1, running_loss, acc))
    

[epoch 1] loss: 48.324, acc: 0.793
[epoch 2] loss: 45.374, acc: 0.797
[epoch 3] loss: 42.759, acc: 0.812
[epoch 4] loss: 40.594, acc: 0.803
[epoch 5] loss: 39.191, acc: 0.803
[epoch 6] loss: 36.069, acc: 0.804
[epoch 7] loss: 33.816, acc: 0.826
[epoch 8] loss: 31.713, acc: 0.848
[epoch 9] loss: 29.947, acc: 0.862
[epoch 10] loss: 29.034, acc: 0.874
[epoch 11] loss: 27.665, acc: 0.864
[epoch 12] loss: 25.492, acc: 0.866
[epoch 13] loss: 25.528, acc: 0.861
[epoch 14] loss: 24.287, acc: 0.893
[epoch 15] loss: 23.209, acc: 0.893
[epoch 16] loss: 21.817, acc: 0.895
[epoch 17] loss: 20.894, acc: 0.896
[epoch 18] loss: 19.246, acc: 0.914
[epoch 19] loss: 18.526, acc: 0.918
[epoch 20] loss: 17.089, acc: 0.921
CPU times: user 9min 8s, sys: 4min 30s, total: 13min 39s
Wall time: 13min 42s
